### ISSUE TITLE
Il est possible de zoomer à l'infini sur la carte

### ISSUE THREAD

**Issue by MathiasBayon** [mvialette/enjoy_diving#4]
Il est possible de zoomer à l'infini sur la carte.
A la fin, l'écran est uniformément gris, et il faut dézoomer longtemps avant de retrouver l’affichage de la carte :-D

**Comment by mvialette** [comment]
Corrigé dans la version : 0.0.3+05082214 (ou supérieur)
Prochainement disponible pour déploiement
